[tool.bumpversion]
current_version = "0.0.20"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""
