[tool.bumpversion]
current_version = "0.0.23"
commit = true
tag = true
pre_commit_hooks = [
  # update lockfile with new version
  "cargo check",
  "cargo update --frozen"
]
additional_files = [
  "Cargo.lock"
]

[[tool.bumpversion.files]]
filename = "Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""
