[files]
ignore-files = true
extend-exclude = [
  # Generated docs assets contain syntax classes and captured terminal output.
  "docs/assets/**/*",
]

[default]
extend-ignore-re = [
  # "spellcheck:ignore-line" ignores the current line.
  "(?Rm)^.*(#|//|--|<!--)\\s*spellcheck:ignore-line(\\s*-->)?\\s*$",

  # "spellcheck:ignore-next-line" ignores the next line.
  "(?Rm)^.*(#|//|--|<!--)\\s*spellcheck:ignore-next-line.*?\\n.*?$",

  # "spellcheck:ignore-block" ignores the following block, ending at the first empty line.
  "(?s)(#|//|--|<!--)\\s*spellcheck:ignore-block(.*?)(?:(?:\\r*\\n){2})",

  # Ignore everything between "spellcheck:ignore-start" and "spellcheck:ignore-end".
  "(?s)(#|//|--|<!--)\\s*spellcheck:ignore-start.*?\\n.*?(#|//|--|<!--)\\s*spellcheck:ignore-end",
]
