name: setup feature combinations
description: Install cargo-feature-combinations
author: romnn <contact@romnn.com>
branding:
  icon: box
  color: orange
inputs:
  version:
    description: Version to install (defaults to the version of the action)
  token:
    description: Github API token
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Install cargo-feature-combinations
      uses: romnn/action-release-download@main
      with:
        version: "latest"
        repo: romnn/cargo-feature-combinations
        expected-matching-asset-count: 2
        # prettier-ignore
        assets: |
          - >-
            *cargo-*
            {{~#switch platform ~}}
              {{~#case "win32"~}}windows{{~/case~}}
              {{~#default~}}{{~platform~}}{{~/default~}}
            {{~/switch~}}
            _
            {{~#switch arch ~}}
            {{~#case "x64"~}}amd64{{~/case~}}
            {{~#default~}}{{~arch~}}{{~/default~}}
            {{~/switch~}}
            *
