name: setup feature combinations
description: Install cargo-feature-combinations
author: romnn <contact@romnn.com>
branding:
  icon: box
  color: orange
inputs:
  version:
    description: Version to install (defaults to the version of the action)
  token:
    description: Github API token
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
