name: setup feature combinations
description: Install cargo-feature-combinations
author: romnn <contact@romnn.com>
branding:
  icon: box
  color: orange
inputs:
  version:
    description: Version to install (defaults to the version of the action)
  token:
    description: Github API token
    default: ${{ github.token }}
# runs:
#   using: node20
#   main: dist/index.js
runs:
  using: "composite"
  steps:
    - name: Install cargo-feature-combinations
      uses: romnn/action-release-download@main
      with:
        version: "latest"
        # prettier-ignore
        assets: |
          - >-
            cargo-*
            {{~#switch platform ~}}
              {{~#case "win32"~}}windows{{~/case~}}
              {{~#default~}}{{~platform~}}{{~/default~}}
            {{~/switch~}}
            _
            {{~#switch arch ~}}
            {{~#case "x64"~}}amd64{{~/case~}}
            {{~#default~}}{{~arch~}}{{~/default~}}
            {{~/switch~}}

      # repo: romnn/cargo-feature-combinations
      # cargo-fc_${trimPrefix(version, "v")}_${platform}_${arch}.${extension}
    # uses: baptiste0928/cargo-install@v3
    # - name: Install cargo-hack from crates.io
    #   uses: baptiste0928/cargo-install@v3
    #   with:
    #     crate: cargo-hack
    #     version: "latest"
    # - name: Set Greeting
    #   run: echo "Hello $INPUT_WHO_TO_GREET."
    #   shell: bash
    #   env:
    #     INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
    #
    # - name: Random Number Generator
    #   id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
    #
    # - name: Set GitHub Path
    #   run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    #   shell: bash
    #   env:
    #     GITHUB_ACTION_PATH: ${{ github.action_path }}
    #
    # - name: Run goodbye.sh
    #   run: goodbye.sh
    #   shell: bash
