[package]
name = "cargo-feature-combinations"
version = "0.0.0"
edition = "2021"
authors = ["romnn <contact@romnn.com>"]
description = "run cargo commands for all feature combinations"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/romnn/cargo-feature-combinations"
repository = "https://github.com/romnn/cargo-feature-combinations"
categories = [ "encoding" ]
keywords = [
  "serde",
  "json",
  "merge",
  "sort",
  "iter"
]
exclude = []

[dependencies]
anyhow = "1"
cargo_metadata = "0"
serde = "1"
serde_json = "1"
itertools = "0"
termcolor = "1"
regex = "1"
lazy_static = "1"
strip-ansi-escapes = "0"

[dev-dependencies]
pretty_assertions = "1"
