[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
c = "check --workspace --all-targets"
t = "nextest run -P default --retries 0 --no-tests warn --all-targets"
lint = "clippy --all-targets --no-deps"
fixit = "clippy --fix --allow-dirty --allow-staged --all-targets --no-deps"
