name: build
on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]
  schedule:
    # 8AM first day of the month in JAN and JUNE to keep workflow badges up-to-date
    - cron: "0 8 1 1,6 *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: task build --output group --output-group-error-only

  cross-compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          # brew install zig
          URL=https://ziglang.org/download/0.13.0/zig-macos-aarch64-0.13.0.tar.xz
          curl -L "${URL}" | tar -xJ
          sudo mv zig-macos-aarch64-0.13.0/zig /usr/bin/zig
      - run: brew install goreleaser
      - name: Release
        run: task build:goreleaser
