# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: build
on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  MISE_GITHUB_TOKEN: ${{ github.token }}
  MISE_AUTO_INSTALL: "0"

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v4
        with:
          install: false
          cache: true
          env: false
      - run: mise install task
      - name: Release (dry-run)
        run: task build:goreleaser
