name: lint
on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]
  schedule:
    # 8AM first day of the month in JAN and JUNE to keep workflow badges up-to-date
    - cron: "0 8 1 1,6 *"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: task dev:tools:install --output group --output-group-error-only
      - name: Audit
        run: task audit --output group --output-group-error-only
      - name: Check for unused dependencies
        run: task unused-dependencies --output group --output-group-error-only
      - name: Lint
        run: task lint --output group --output-group-error-only

  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install goreleaser
      - name: Check goreleaser config
        run: goreleaser check

  spellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@stable
      - run: task dev:tools:install --output group --output-group-error-only
      - name: Spellcheck
        run: task spellcheck --output group --output-group-error-only
