name: release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  publish-crate:
    runs-on: ubuntu-24.04
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish crates
        uses: romnn/publish-crates@main
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          resolve-versions: true
          publish-delay: 30s

  release:
    runs-on: ubuntu-24.04
    needs: [tests]
    outputs:
      precompiled-binaries: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "3.42.1"
      - name: Release
        run: task release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TAP_GITHUB_TOKEN: "${{ secrets.TAP_GITHUB_TOKEN }}"
      - name: Upload precompiled binaries
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-dist
          path: goreleaser-dist
