name: test-action
on:
  push:
    tags-ignore:
      - "**"
jobs:
  feature-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.feature-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: romnn/cargo-feature-combinations@main
      - name: Compute feature matrix
        id: feature-matrix
        run: >-
          echo "matrix=$(cargo fc matrix)" >> "$GITHUB_OUTPUT"
      - name: Print feature matrix
        run: |
          echo "${{ steps.feature-matrix.outputs.matrix }}"
  test-features:
    name: test ${{ matrix.package.name }} (${{ matrix.package.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: >-
          cargo test --package "${{ matrix.package.name }}" --features "${{ matrix.package.features }}" --all-targets
