name: test

on: [push, pull_request, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test
        run: cargo test --all-targets

      - name: Lint
        continue-on-error: true
        run: >-
          cargo clippy
          --tests
          --benches
          --examples
          -- -Dclippy::all -Dclippy::pedantic
