name: test

on: [push, pull_request, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test --all-targets

      - name: Lint
        continue-on-error: true
        run: >-
          cargo clippy
          --tests
          --benches
          --examples
          -- -Dclippy::all -Dclippy::pedantic

  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./
        env:
          # github only sets this for non local actions
          GITHUB_ACTION_REPOSITORY_OVERRIDE: romnn/cargo-feature-combinations

      - name: Compute feature matrix
        run: >-
          echo "matrix=$(cargo fc matrix)" >> $GITHUB_OUTPUT

  publish:
    name: publish (dry-run)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish crates (dry-run)
        uses: romnn/publish-crates@main
        with:
          dry-run: true
          resolve-versions: true
