# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: test-action
on:
  push: {}
  workflow_call: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  feature-matrix:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    outputs:
      matrix: ${{ steps.feature-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build cargo-fc from the working tree
        run: cargo build --locked --bin cargo-fc
      - name: Compute feature matrix
        id: feature-matrix
        run: >-
          echo "matrix=$(target/debug/cargo-fc --no-targets matrix)" >> "$GITHUB_OUTPUT"
      - name: Print feature matrix
        run: |
          echo "${{ steps.feature-matrix.outputs.matrix }}"

  test-features:
    name: test ${{ matrix.package.name }} (${{ matrix.package.features }})
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Test
        # prettier-ignore
        run: >-
          cargo test
          --package "${{ matrix.package.name }}"
          --features "${{ matrix.package.features }}"
          --all-targets

  test-action:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: Download and install cargo-feature-combinations via local action
        uses: ./
      - name: Test installation
        run: cargo fc --help
